# Generated by Django 4.2.6 on 2024-04-28 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('LocationID', models.IntegerField(primary_key=True, serialize=False)),
                ('Address', models.CharField(max_length=300)),
                ('Name', models.CharField(max_length=100)),
                ('Latitude', models.FloatField(null=True)),
                ('Longitude', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shows',
            fields=[
                ('Version', models.FloatField()),
                ('ShowID', models.IntegerField(primary_key=True, serialize=False)),
                ('UID', models.CharField(max_length=50)),
                ('Title', models.CharField(max_length=100)),
                ('Category', models.IntegerField()),
                ('ShowUnit', models.IntegerField(null=True)),
                ('DiscountInfo', models.IntegerField(null=True)),
                ('DescriptionFilterHtml', models.CharField(max_length=3000, null=True)),
                ('ImageUrl', models.CharField(max_length=300, null=True)),
                ('WebSales', models.CharField(max_length=300, null=True)),
                ('SourceWebPromote', models.CharField(max_length=300, null=True)),
                ('Comment', models.CharField(max_length=3000, null=True)),
                ('EditModifyDate', models.DateTimeField(null=True)),
                ('SourceWebName', models.CharField(max_length=50)),
                ('StartDate', models.DateField()),
                ('EndDate', models.DateField()),
                ('HitRate', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Units',
            fields=[
                ('UnitID', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ShowUnitRoles',
            fields=[
                ('ShowUnitRoleID', models.IntegerField(primary_key=True, serialize=False)),
                ('Role', models.CharField(max_length=20)),
                ('ShowID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shows.shows')),
                ('UnitID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shows.units')),
            ],
        ),
        migrations.CreateModel(
            name='ShowInfos',
            fields=[
                ('ShowInfoID', models.IntegerField(primary_key=True, serialize=False)),
                ('Time', models.DateTimeField()),
                ('OnSales', models.CharField(max_length=1)),
                ('Price', models.CharField(max_length=300, null=True)),
                ('EndTime', models.DateTimeField()),
                ('LocationID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shows.locations')),
                ('ShowID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shows.shows')),
            ],
        ),
    ]
