# Generated by Django 4.2.6 on 2024-04-28 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shows',
            name='ShowUnit',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
