# Generated by Django 4.2.6 on 2024-04-28 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0002_alter_shows_showunit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shows',
            name='DiscountInfo',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
