# Generated by Django 4.2.6 on 2024-04-28 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0003_alter_shows_discountinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shows',
            name='UID',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
