# Generated by Django 4.2.6 on 2024-04-28 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0004_alter_shows_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locations',
            name='LocationID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='showinfos',
            name='ShowInfoID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='shows',
            name='ShowID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='showunitroles',
            name='ShowUnitRoleID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='units',
            name='UnitID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
