# Generated by Django 4.2.6 on 2024-04-28 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0005_alter_locations_locationid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showinfos',
            name='Price',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='shows',
            name='Comment',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='shows',
            name='DescriptionFilterHtml',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='shows',
            name='DiscountInfo',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='shows',
            name='ImageUrl',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='shows',
            name='ShowUnit',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='shows',
            name='SourceWebPromote',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='shows',
            name='WebSales',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
