# Generated by Django 4.2.6 on 2024-04-28 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0006_alter_showinfos_price_alter_shows_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shows',
            name='Category',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='shows',
            name='Version',
            field=models.CharField(max_length=10),
        ),
    ]
